version: "3.7"

services:
  api_gateway:
    build:
      context: .
    container_name: api_gateway
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    restart: on-failure
